export const cryptoSlateConfig = {
  selectors: {
    newsContainer: ".news-feed .list-feed",
    newsItem: ".list-post article",
    title: ".list-post .title h2",
    description: ".list-post .excerpt p",
    category: ".list-post .post-meta span:first-child",
    author: "",
    date: ".list-post .post-meta span.read",
    link: ".list-post article a",
    image: ".list-post .cover img",
    contentType: ".list-post .post-meta span.type",
  },
  url: "https://cryptoslate.com/news/",
  articleSelectors: {
    content: ".post-box article",
    title: "h1.post-title",
    subtitle: "p.post-subheading",
    author: ".post-author .author-info a",
    date: ".post-date",
    category: ".post-category .news-cats a, .big-cat a",
    tags: ".post-meta-items .tags a",
    image: ".cover img",
    imageCaption: ".cover .caption p",
    paragraphs: "article p",
    headers: "article h2, article h3",
    lists: "article ul, article ol",
    listItems: "article li",
    blockquotes: "article blockquote",
    readingTime: ".span-reading-time",
    updated: ".post-reading .post-date",
    shareButtons: ".social-sharing .container a",
  },
};
